#!/bin/bash

# This file is part of the competition environment.
#
# SPDX-FileCopyrightText: 2011-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generate PHP code for the competition web site to print tool names with links to the project web site.

echo "<?php
";

DIR="$(dirname "$0")"
CATEGORY_STRUCTURE="$DIR/../../benchmark-defs/category-structure.yml"
YEAR=$(yq --raw-output '.year' "$CATEGORY_STRUCTURE")
COMPETITIONNAME=$(yq --raw-output '.competition' "$CATEGORY_STRUCTURE")

echo "# This is generated by $0. Do not change manually.";

yq --raw-output \
      "select(.competition_participations[]?
              | .competition==\"$COMPETITIONNAME $YEAR\" and (.label | index(\"auxiliary\") | not)
             )
       | [.id, .name]
       | join(\";\")" \
      "$DIR"/../../fm-tools/data/*.yml \
| sort -u \
| while IFS=';' read TOOLID TOOLNAME; do
    TOOLFUNC=${TOOLID//[2]/two}
    TOOLFUNC=${TOOLFUNC/[4]/}
    TOOLFUNC=${TOOLFUNC//[+]/p}
    TOOLFUNC=${TOOLFUNC//\-/}
    echo "function ${TOOLFUNC,,}${YEAR}() {";
    echo "  echo '<a href=\"https://fm-tools.sosy-lab.org/#tool-$TOOLID\">$TOOLNAME</a>';";
    echo "}";
    echo "";
  done

echo "
?>";
