#!/bin/bash

# This file is part of the competition environment.
#
# SPDX-FileCopyrightText: 2011-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Creates the table of participating teams for the competition website. Data are fetched from the FM-Tools repository. 

DIR="$(dirname "$0")"
CATEGORY_STRUCTURE="$DIR/../../benchmark-defs/category-structure.yml"
YEAR=$(yq --raw-output '.year' "$CATEGORY_STRUCTURE")
COMPETITIONNAME=$(yq --raw-output '.competition' "$CATEGORY_STRUCTURE")
TARGETSERVER=$(echo "$COMPETITIONNAME" | tr A-Z a-z)

MAIN_TRACK="Verification"
if [[ "$COMPETITIONNAME" == "Test-Comp" ]]; then
  MAIN_TRACK="Test Generation"
fi

NEW_VERIFIERS="$(yq --raw-output \
                "select( .competition_participations[]?
                         | (.competition | startswith(\"$COMPETITIONNAME\"))
                           and .track==\"$MAIN_TRACK\"
                           and (.label | index(\"auxiliary\") | not)
                       )
                 | select( [.competition_participations[]? | .competition==\"$COMPETITIONNAME $YEAR\"]
                           | all
                         )
                 | .id" \
          "$DIR"/../../fm-tools/data/*.yml | xargs)"

NEW_VALIDATORS="$(yq --raw-output \
                "select( .competition_participations[]?
                         | (.competition | startswith(\"$COMPETITIONNAME\"))
                           and .track!=\"$MAIN_TRACK\"
                           and (.label | index(\"auxiliary\") | not)
                       )
                 | select( [.competition_participations[]? | .competition==\"$COMPETITIONNAME $YEAR\"]
                           | all
                         )
                 | .id" \
          "$DIR"/../../fm-tools/data/*.yml | xargs)"


echo "<!-- This file is generated by $0. Do not edit manually. -->";

echo "

<h2>Tools for $MAIN_TRACK</h2>

<table>
  <tr style='font-weight: bold;'>
    <td>Tool</td>
    <td>Lang.</td>
    <td>Jury member</td>
    <td>Affiliation</td>
    <td>Archive</td>
    <td>Benchmark definition</td>
  </tr>
  <tr>
    <td style='font-size: 80%; font-weight: bold;' width="130px">
      Overview
    </td>
    <td style='font-size: 70%;'>
      Chair
    </td>
    <td style='font-size: 70%;'>
      <a href='https://www.sosy-lab.org/~dbeyer/'>Dirk Beyer</a>
    </td>
    <td style='font-size: 70%;'>
      LMU Munich, Germany
    </td>
    <td style='font-size: 70%';>
 
    </td>
    <td style='font-size: 70%';>

    </td>
    <td>
      <!--<a href="https://www.sosy-lab.org/research/prs/2019-04-06_SV-COMP_Dirk.pdf">talk</a>-->
    </td>
  </tr>
";

yq --raw-output \
  "select( .competition_participations[]?
               | .competition==\"$COMPETITIONNAME $YEAR\" and .track==\"$MAIN_TRACK\" and (.label | index(\"auxiliary\") | not)
              )
       | .id as \$id
       | .name as \$name
       | (.input_languages | join(\", \")) as \$languages
       | . as \$tool
       | .competition_participations[]?
       | select(.competition==\"$COMPETITIONNAME $YEAR\" and .track==\"$MAIN_TRACK\")
       | .tool_version as \$tool_version
       | (\$tool.versions [] | select(.version == \$tool_version) | .doi) as \$doi
       | [\$id, \$name, \$languages, .jury_member.name, .jury_member.institution, .jury_member.country, .jury_member.orcid, \$doi, if .label==null then \"\" else (.label | join(\",\")) end]
       | join(\";\")" \
      "$DIR"/../../fm-tools/data/*.yml \
  | sort -u \
  | while IFS=';' read TOOLID TOOLNAME TOOLLANG MEMBERNAME MEMBERINST MEMBERCOUNTRY ORCID TOOLDOI LABEL; do
      # echo              "$TOOLID $TOOLNAME $TOOLLANG $MEMBERNAME $MEMBERINST $MEMBERCOUNTRY $ORCID $TOOLDOI $LABEL"
      echo "  <tr>";
      TOOLFUNC="${TOOLID//[2]/two}$YEAR"
      TOOLFUNC="${TOOLFUNC/[4]/}"
      TOOLFUNC=${TOOLFUNC//[+]/p}
      TOOLFUNC="${TOOLFUNC//\-/}"
      TOOLFUNC="${TOOLFUNC,,}$YEAR"
      TOOLDOI_ID=${TOOLDOI#10.5281/zenodo.}
      DECORATION=""
      if [[ "$LABEL" =~ "inactive" ]]; then
        DECORATION="$DECORATION <sup style='color: violet;'>∅</sup>"
      fi
      if [[ "$LABEL" =~ "meta_tool" ]]; then
        DECORATION="$DECORATION <sup style='color: green;'>meta</sup>"
      fi
      if [[ "${NEW_VERIFIERS// /;};" =~ "$TOOLID;" ]]; then
        DECORATION="$DECORATION <sup style='color: orange;'>new</sup>"
      fi
      echo "    <td style='font-size: 80%; font-weight: bold;'>";
      echo "      <a href=\"https://fm-tools.sosy-lab.org/#tool-$TOOLID\">$TOOLNAME</a>$DECORATION";
      echo "    </td>";
      echo "    <td style='font-size: 70%;'>";
      echo "      $TOOLLANG";
      echo "    </td>";
      if [[ "$LABEL" =~ "inactive" ]]; then
        echo "    <td style='font-size: 70%;'>inactive</td>";
        echo "    <td/>";
      else
        echo "    <td style='font-size: 70%;'>";
        echo "      <a href='https://orcid.org/$ORCID'>$MEMBERNAME</a>";
        echo "    </td>";
        echo "    <td style='font-size: 70%;'>";
        echo "      $MEMBERINST, $MEMBERCOUNTRY";
        echo "    </td>";
      fi
      echo "    <td style='font-size: 70%';>";
      echo "      <a href='https://doi.org/$TOOLDOI'>$TOOLDOI_ID</a>";
      echo "    </td>";
      echo "    <td style='font-size: 70%';>";
      echo "      <a href='https://gitlab.com/sosy-lab/$TARGETSERVER/bench-defs/blob/${TARGETSERVER/-/}${YEAR#??}/benchmark-defs/$TOOLID.xml'>$TOOLID.xml</a>";
      echo "    </td>";
      echo "  </tr>";
    done
echo "
</table>
";

echo "

<h2>Tools for Validation</h2>

<table>
  <tr style='font-weight: bold;'>
    <td>Tool</td>
    <td>Lang.</td>
    <td>Format</td>
    <td>Jury member</td>
    <td>Affiliation</td>
    <td>Archive</td>
    <td>Benchmark definition</td>
  </tr>
";

yq --raw-output \
  "select( .competition_participations[]?
               | .competition==\"$COMPETITIONNAME $YEAR\" and .track!=\"$MAIN_TRACK\" and (.label | index(\"auxiliary\") | not)
              )
       | .id as \$id
       | .name as \$name
       | (.input_languages | join(\", \")) as \$languages
       | . as \$tool
       | .competition_participations[]?
       | select(.competition==\"$COMPETITIONNAME $YEAR\" and .track!=\"$MAIN_TRACK\")
       | .tool_version as \$tool_version
       | (\$tool.versions [] | select(.version == \$tool_version) | .doi) as \$doi
       | [\$id, \$name, \$languages, .jury_member.name, .jury_member.institution, .jury_member.country, .jury_member.orcid, \$doi, if .label==null then \"\" else (.label | join(\",\")) end]
       | join(\";\")" \
      "$DIR"/../../fm-tools/data/*.yml \
  | sort -u \
  | while IFS=';' read TOOLID TOOLNAME TOOLLANG MEMBERNAME MEMBERINST MEMBERCOUNTRY ORCID TOOLDOI LABEL; do
      # echo              "$TOOLID $TOOLNAME $TOOLLANG $MEMBERNAME $MEMBERINST $MEMBERCOUNTRY $ORCID $TOOLDOI $LABEL"
      echo "  <tr>";
      TOOLFUNC="${TOOLID//[2]/two}$YEAR"
      TOOLFUNC="${TOOLFUNC/[4]/}"
      TOOLFUNC="${TOOLFUNC//\-/}"
      TOOLFUNC="${TOOLFUNC,,}$YEAR"
      TOOLDOI_ID=${TOOLDOI#10.5281/zenodo.}
      TOOLTRACKS=$(yq --raw-output \
                     ".versions as \$versions
                      | [.competition_participations []
                         | select(.competition == \"$COMPETITIONNAME $YEAR\" and .track != \"$MAIN_TRACK\")
                         | .tool_version as \$tool_version
                         | select(\$versions []
                                  | .version==\$tool_version and .doi==\"$TOOLDOI\")
                         | .track
                        ]
                      | join(\", \")" \
                     "$DIR"/../../fm-tools/data/"$TOOLID".yml \
                     | sed -e "s/Validation of //g" -e "s/Witnesses //g" -e "s/Test Suites //g")
      DECORATION=""
      if [[ "$LABEL" =~ "inactive" ]]; then
        DECORATION="$DECORATION <sup style='color: violet;'>∅</sup>"
      fi
      if [[ "$LABEL" =~ "meta_tool" ]]; then
        DECORATION="$DECORATION <sup style='color: green;'>meta</sup>"
      fi
      if [[ "${NEW_VALIDATORS// /;};" =~ "$TOOLID;" ]]; then
        DECORATION="$DECORATION <sup style='color: orange;'>new</sup>"
      fi
      echo "    <td style='font-size: 80%; font-weight: bold;'>";
      echo "      <a href=\"https://fm-tools.sosy-lab.org/#tool-$TOOLID\">$TOOLNAME</a>$DECORATION";
      echo "    </td>";
      echo "    <td style='font-size: 70%;'>";
      echo "      $TOOLLANG";
      echo "    </td>";
      echo "    <td style='font-size: 70%;'>";
      echo "      $TOOLTRACKS";
      echo "    </td>";
      if [[ "$LABEL" =~ "inactive" ]]; then
        echo "    <td style='font-size: 70%;'>inactive</td>";
        echo "    <td/>";
      else
        echo "    <td style='font-size: 70%;'>";
        echo "      <a href='https://orcid.org/$ORCID'>$MEMBERNAME</a>";
        echo "    </td>";
        echo "    <td style='font-size: 70%;'>";
        echo "      $MEMBERINST, $MEMBERCOUNTRY";
        echo "    </td>";
      fi
      echo "    <td style='font-size: 70%';>";
      echo "      <a href='https://doi.org/$TOOLDOI'>$TOOLDOI_ID</a>";
      echo "    </td>";
      echo "    <td style='font-size: 70%';>";
      echo "      <a href='https://gitlab.com/sosy-lab/$TARGETSERVER/bench-defs/blob/${TARGETSERVER/-/}${YEAR#??}/benchmark-defs/$TOOLID.xml'>$TOOLID.xml</a>";
      echo "    </td>";
      echo "  </tr>";
    done
echo "
</table>
";
