#!/bin/bash

# This file is part of the competition environment.
#
# SPDX-FileCopyrightText: 2011-2025 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generate committee-listing web page for the competition web site.

DIR="$(dirname "$0")"
CATEGORY_STRUCTURE="$DIR/../../benchmark-defs/category-structure.yml"
YEAR=$(yq --raw-output '.year' "$CATEGORY_STRUCTURE")
COMPETITIONNAME=$(yq --raw-output '.competition' "$CATEGORY_STRUCTURE")
MAIN_TRACK="Verification"
if [[ "$COMPETITIONNAME" == "Test-Comp" ]]; then
  MAIN_TRACK="Test Generation"
fi

echo "<!-- This is generated by $0. Do not change manually. -->";

yq --raw-output --slurp \
  "map(select( .competition_participations[]?
               | .competition==\"$COMPETITIONNAME $YEAR\"
                 and (.label | index(\"auxiliary\") | not) and (.label | index(\"inactive\") | not)
              )
       | .id as \$id
       | .name as \$name
       | (.input_languages | join(\", \")) as \$languages
       | . as \$tool
       | .competition_participations[]?
         | select(.competition==\"$COMPETITIONNAME $YEAR\")
         | .tool_version as \$tool_version
         | (\$tool.versions [] | select(.version == \$tool_version) | .doi) as \$doi
         | [\$id, \$name, \$languages, .jury_member.name, .jury_member.institution, .jury_member.country, .jury_member.orcid, .label[0]]
         | join(\";\")
      )
      | .[]" \
      "$DIR"/../../fm-tools/data/*.yml \
  | sort -u \
  | while IFS=';' read TOOLID TOOLNAME TOOLLANG MEMBERNAME MEMBERINST MEMBERCOUNTRY ORCID LABEL; do
      # echo              "$TOOLID $TOOLNAME $TOOLLANG $MEMBERNAME $MEMBERINST $MEMBERCOUNTRY $ORCID $LABEL"
      if [[ "$LABEL" == "inactive" ]]; then
        continue
      fi
      TOOLFUNC=${TOOLID//[2]/two}
      TOOLFUNC=${TOOLFUNC/[4]/}
      TOOLFUNC=${TOOLFUNC//[+]/p}
      TOOLFUNC=${TOOLFUNC//\-/}
      echo "  <li>";
      if [[ "$LABEL" != "inactive" ]]; then
        echo "      <a href='https://orcid.org/$ORCID'>$MEMBERNAME</a>";
        echo "      (representing <?php ${TOOLFUNC,,}${YEAR}() ?>), $MEMBERINST, $MEMBERCOUNTRY";
      fi
      echo "  </li>";
    done
